# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('course', '0002_auto_20170218_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
    ]
