# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_plan_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='travel_buddy',
            new_name='users',
        ),
    ]
